### ISSUE TITLE
Changing Unique Body Parts After Starting to Label

### ISSUE THREAD

**Issue by tom221085** [DeepLabCut/napari-deeplabcut#111]
I started labelling and training but then decided to change and add the unique bodyparts. Unfortunately, it doesn't change it in my already labeled data. Is there a solution for this?

**Comment by jeylau** [comment]
Hi @tom221085, after editing your config.yaml file, did you load it in the GUI (i.e., as explained in Step 2 of the [Workflow](https://github.com/DeepLabCut/napari-deeplabcut?tab=readme-ov-file#workflow))? This is necessary to update the menus and the loaded data, so after saving the h5 file should properly include the new body parts.

**Comment by tom221085** [comment]
Hi jeylau! Yes, I did that and the problem was solved. Sorry! I forgot to close this issue. Thanks!

**Comment by jeylau** [comment]
No worries, glad to hear you solved it!
