### ISSUE TITLE
Add option to jump to certain frame

### ISSUE THREAD

**Issue by hummuscience** [DeepLabCut/napari-deeplabcut#112]
More of a quality of life upgrade. But it would be nice to have the option to jump to a certrain frame in the GUI

**Comment by jeylau** [comment]
Hi @hummuscience, this is something you can already do: one can edit the current frame number (by double-clicking on it) and input the frame you want to jump to. I'll add it to the docs!

<img width="970" alt="screenshot" src="https://github.com/DeepLabCut/napari-deeplabcut/assets/30733203/f44a1e3f-ed58-42c1-b983-fdaa401ac82d">

**Comment by hummuscience** [comment]
Ah, I tried that and it didnt work. Maybe I was on an old version? Anyway, will give it a try and let you know

**Comment by jeylau** [comment]
Hi @hummuscience, could you make it work?

**Comment by hummuscience** [comment]
Forgot about it! will give it a try today and report back, sorry

**Comment by jeylau** [comment]
No worries!

**Comment by hummuscience** [comment]
Yes, it works! I think what confused me is that there is no UI feedback that one can change the frame (like a cursor or something). When I double click the number, it just highlights the number. So I wouldn't "think" its possible to change >.<

Does that make sense?

Anyway. Thanks!
