### ISSUE TITLE
napari doesn't show any images (visibility toggle option is not available)

### ISSUE THREAD

**Issue by mirramezani** [DeepLabCut/napari-deeplabcut#113]
When I try to open an image in napari the icon comes (with visibility toggle unavailable) but nothing is shown in the main panel. The images was extracted by deeplabcut (so I'm sure they're supported by napari). My napari is not able to show any images. I want to know what's wrong with that!
![Untitled](https://github.com/DeepLabCut/napari-deeplabcut/assets/159242970/b3ce02f4-50aa-4204-93d6-c61cedc2fea9)

**Comment by jeylau** [comment]
Hello! Try loading the entire folder of images (i.e., one found under /labeled-data) as explained in the [Workflow](https://github.com/DeepLabCut/napari-deeplabcut?tab=readme-ov-file#workflow), rather than the image files directly.

**Comment by MMathisLab** [comment]
The icon is actually deactivated (not sure why)

**Comment by jeylau** [comment]
@MMathisLab, some slight incompatibility with pyside6 left in napari (the icon does not toggle, though it is functional).

**Comment by mirramezani** [comment]
Thank you so much for responce @jeylau @MMathisLab . I did as you said but it's still the same. I don't know what to do.

**Comment by MMathisLab** [comment]
can you try to update the app @mirramezani ? How many images do you have, as I don't see the usual scroll bar on the bottom either...

**Comment by mirramezani** [comment]
@MMathisLab I just updated to the version 4.19.0 and still the same. I've tried both single and multiple like 10 images, but no difference, nothing is shown.

**Comment by jeylau** [comment]
@mirramezani, stay with `napari==0.4.18`, we haven't tested napari's newest version. Make sure though that you install the latest version of our labeling plugin with `pip install -U napari-deeplabcut`.

**Comment by mirramezani** [comment]
@jeylau oh I see, ok I'll downgrade to 4.18.0 and will be waiting for further solution.
