### ISSUE TITLE
poor/confusing workflow for saving data ?

### ISSUE THREAD

**Issue by MMathisLab** [DeepLabCut/napari-deeplabcut#12]
## Fix needed for saving. ...

Right now saving is painfully slow because it's manual. I don't quite understand the workflow; I open a DLC labeled-data folder (single folder). I either add points, or let's say I open the demo mont blanc data, move a point around and click ctrl+S; I then get a dialog box, whereas this should autosave into the H5 + CSV!

<img width="869" alt="Screen Shot 2022-06-03 at 12 44 40 AM" src="https://user-images.githubusercontent.com/28102185/171751062-fc2efbd3-5936-4047-bffe-222577af46f2.png">

Even more confusing, I "saved" a CollectedData_test to check what was happening, but it does not save, and rather the files are updated? The file choices are also very confusing ... can we **NOT** have this pop up for dlc projects that already have a CSV/H5?

**Comment by jeylau** [comment]
I agree, but this cannot be achieved with the plugin (or rather not via the Save Layer action as it is tied to the Save Dialog). Perhaps a solution would be to have an alternative save button in the dock widget, bypassing napari saving mechanism.

**Comment by MMathisLab** [comment]
yeah we should by-pass this. Also then I am confused still, did it save automatically and the pop up is useless, or?

**Comment by jeylau** [comment]
Yes, exactly. Under the hood we automatically pick the right location/filename and we save under CollectedData_scorer regardless of what's input into the dialog window. Maybe I've found a better way, I'll push something soon.

**Comment by MMathisLab** [comment]
okay great; so it's just the funny pop up that is the "issue" -- that at least reassures me I am not going crazy :) haha
