### ISSUE TITLE
Low resolution image in labeling GUI

### ISSUE THREAD

**Issue by hdsliu** [DeepLabCut/napari-deeplabcut#124]
The resolution of video is good, the extracted frame's resolution is good, but in napari GUI resolution is much lower.
This makes it harder to determine if the body part I want to label is actually in view. 
Is there a way to fix this? I am super new to DLC. 
Thanks!

**Comment by MMathisLab** [comment]
Hi @hdsliu that is strange; can you open an issue in napari? I don't see this fwiw
