### ISSUE TITLE
frames without label are not skipped

### ISSUE THREAD

**Issue by Habedank** [DeepLabCut/napari-deeplabcut#139]
Hi,
we encountered the problem that we reopened a labeled video (i.e., a file with already labeled frames) and found the labels in "strange" places, meaning in frames in which no mouse was seen, still a mouse was labeled. We narrowed the problem down to the following:

In the stored csv file, only the frames are listed in which labels were asigned. Meaning if there was nothing to be labeled, the frame is noot listed. Napari, on the other hand, seems to use just the order of the labels and does not check to which frame it belongs. 

So it's merely a "cosmetic" problem (napari displays it wrong) but all the labels are saved correctly in the csv file. However, this also leads  to the problem, that video for which labeling was already started, can't be continued / corrected later on because the shown labels in napari are all shifted.

Hope this discription somehow helps.

**Comment by jeylau** [comment]
Thanks for reporting the issue @Habedank. Could you please tell me what version of `napari-deeplabcut` you're using?

**Comment by Habedank** [comment]
Of course, sorry. We're using napari version 0.4.18 through deeplabcut (version 2.3.9) and on a Windows 11 computer, in case this might also play a role.

**Comment by jeylau** [comment]
No worries, what is the version of `napari-deeplabcut` specifically that you're using? You can either get it with `pip freeze | grep napari-deeplabcut` or when in the labeling GUI, in the Plugins > Install/Uninstall Plugins menu. I suspect you may be using an old version. Updating with `pip install -U napari-deeplabcut` should normally fix the issue you describe.

**Comment by Habedank** [comment]
We use the version which was automaticaly included when installing deeplabcut in May. The napari-deeplabcut version is 0.2.1.6 according to your instructions (thank you for those). And you were right, in 0.2.1.7  the problem ist fixed. Thank you!

**Comment by jeylau** [comment]
Great to hear! With DeepLabCut 3 onwards, you'll get notified in the GUI if/when a new version of is available.
