### ISSUE TITLE
Question/keypoint size 🐛:  how do I increase the size of all keypoints on an image?

### ISSUE THREAD

**Issue by MMathisLab** [DeepLabCut/napari-deeplabcut#15]
hi @jeylau how can I increase the size of ALL points on an image? Currently, it seems I cannot in napari? I have to click the arrow, then go click on a point, then it increases... this is slow ... 

top: small, but no change;
 middle: large > but no change; 
bottom: click and change....

![Screen Shot 2022-06-03 at 1 41 13 PM](https://user-images.githubusercontent.com/28102185/171847010-d89fc2b7-2a9a-4afb-913a-e780022bae49.png)
![Screen Shot 2022-06-03 at 1 41 19 PM](https://user-images.githubusercontent.com/28102185/171847017-81a4b83b-ea2f-4345-8e58-9f3ac14ed9d7.png)
![Screen Shot 2022-06-03 at 1 41 30 PM](https://user-images.githubusercontent.com/28102185/171847026-d631c7d3-78e2-48e2-b064-9375fbae2f1d.png)

**Comment by jeylau** [comment]
Related to #1
I'll add an extra slider, because I didn't manage to hack it otherwise 😄
