### ISSUE TITLE
order of operations in drag&drop raw images + config.yaml matter

### ISSUE THREAD

**Issue by MMathisLab** [DeepLabCut/napari-deeplabcut#22]
if you drag & drop fresh images first, THEN config.yaml, the keypoint selection box does not show up; requires adding config.yaml first, then raw images. Maybe not an issue per say, but something to keep in mind / update in docs?

**Comment by jeylau** [comment]
I cannot reproduce it @MMathisLab: is an error or something shown in the console?

**Comment by MMathisLab** [comment]
no error for me; maybe I hit a more complex order of ops... will try again later

**Comment by MMathisLab** [comment]
agree, maybe it was too many delete/repeats :) I also cannot reproduce
