### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by goanpeca** [DeepLabCut/napari-deeplabcut#27]
Hi @jeylau, when reviewing https://github.com/conda-forge/napari-deeplabcut-feedstock/pull/1

We found that some of the dependencies might not be updated.

### Packages found by source code inspection but not in the meta.yaml:
pyyaml
scikit-image

### Packages found in the meta.yaml but not found by source code inspection:
pytables
ruamel.yaml

Is this correct?

Perhaps you could update the setup.cfg so the next release includes the correct dependencies.

Cheers!

**Comment by jeylau** [comment]
Hi @goanpeca! scikit-image is rightly defined in the setup.cfg, and tables (although not found in the code) is required by pandas when loading our DeepLabCut data files. For yaml though, you're correct, it should be pyyaml rather than ruamel.yaml, I'll fix it. ☺️

**Comment by goanpeca** [comment]
Thanks @jeylau, BTW do you want to be added as maintainer at https://github.com/conda-forge/napari-deeplabcut-feedstock/pull/1

We are in the process of creating conda packages for [napari plugins](https://www.napari-hub.org/) and related dependencies. Once this recipe passes all the checks, every time a new release goes into PyPI, a PR will be created automatically, with usually very minor need for changes so the process of maintaining this moving forward is small. Also the `@conda-forge/napari` team will be available to help as needed.

You can read a bit more about conda-forge at https://conda-forge.org/#contribute

---

Cheers!

**Comment by jeylau** [comment]
Sorry for the late reply @goanpeca; if maintaining cost of the conda package is small, I can do it!

**Comment by goanpeca** [comment]
Adding you https://github.com/conda-forge/napari-deeplabcut-feedstock/pull/5!
