### ISSUE TITLE
Get rid of the « choose reader » dialog when dropping folders

### ISSUE THREAD

**Issue by jeylau** [DeepLabCut/napari-deeplabcut#3]

**Comment by MMathisLab** [comment]
I assume you mean this? As yes, if you pick either of the top 2 you get an error ...
<img width="735" alt="Screen Shot 2022-06-03 at 12 42 05 AM" src="https://user-images.githubusercontent.com/28102185/171750853-160fbd4e-caec-42b6-b680-0eb121d155f3.png">
