### ISSUE TITLE
Bodypart dropbox should update which bodypart is labeled

### ISSUE THREAD

**Issue by A-Telfer** [DeepLabCut/napari-deeplabcut#39]
I think the dropbox should change to show the next point that will be labeled, and changing the dropbox should change the next point to be labeled

Video shows me selecting a bodypart in the dropdown then labeling, but a different bodypart is added
https://user-images.githubusercontent.com/75952206/189493334-13ba3efb-874b-49f6-9512-3fe2a1d5e3e9.mp4

Enjoying the new UI! Just being able to use basic hotkeys and c+p datapoints is already speeding things up a lot.

**Comment by jeylau** [comment]
Hey @A-Telfer, I think I just fixed it with [51d1b56](https://github.com/DeepLabCut/napari-deeplabcut/commit/51d1b5645b854a1ed9a7682f69992b9746be06d6). You could try it out with `pip install -U git+https://github.com/DeepLabCut/napari-deeplabcut.git` 😃.

**Comment by felixhol** [comment]
[51d1b56](https://github.com/DeepLabCut/napari-deeplabcut/commit/51d1b5645b854a1ed9a7682f69992b9746be06d6) indeed fixes this - thanks!!!

**Comment by MMathisLab** [comment]
super - @jeylau let's make a new release of this package

**Comment by jeylau** [comment]
@MMathisLab, sure! I'd just like to hear from https://github.com/DeepLabCut/napari-deeplabcut/issues/41#issue-1409590097 to make sure it's now error-free.

**Comment by jeylau** [comment]
> super - @jeylau let's make a new release of this package

Done
