### ISSUE TITLE
Keypoint annotation changing when labeling - Multi Animal

### ISSUE THREAD

**Issue by weertman** [DeepLabCut/napari-deeplabcut#40]
Dear awesome people who are working on napari-deeplabcut. First off thank you! Napari runs on my computer so smoothly while the DLC GUI crashes. 

I have been labelling field of worms (<200 individuals). Sometimes I mess up and have to delete an annotation. When I do this using the pointer tool and then start re-annotating the sequence of annotations gets bumped forwards once from what I am expecting. Sometimes. Manually setting which annotation I am on does not prevent this behavior. If I delete multiple previous annotations and then click off the image, then manually enter what my annotation is, it seems to work correctly. 

Cheers and thanks! keep up the good work. the DLC GUI lights my computer on fire when annotating hundreds of individuals while napari-deeplabcut just hums along easily.

**Comment by jeylau** [comment]
Hello @weertman, thank you for the very kind words!
I couldn't replicate the behavior you described. I tried the following:
- annotate some keypoints, select one (either clicking on it or using the rectangular selector): this should update the dropdown menus to the correct individual and body part names. If I now label a point, the point just deleted gets added back. If I select multiple points though, the dropdown menus are not updated and labeling then resumes from where you last stopped.
Just out of curiosity, what version of the plugin are you running?
Could you maybe upload a short GIF or video that shows the bug you're experiencing, it's likely that I understood it wrong 😅

**Comment by jeylau** [comment]
I have just now spotted something similar to what you experienced. It's now fixed with [51d1b56](https://github.com/DeepLabCut/napari-deeplabcut/commit/51d1b5645b854a1ed9a7682f69992b9746be06d6). You could try it out with `pip install -U git+https://github.com/DeepLabCut/napari-deeplabcut.git`; let me know if you still face the issue afterwards!

**Comment by weertman** [comment]
Hey Jaylau,

I think I explained it poorly. Here is a video of the error. It happens when I switch to the arrow tool to move around points and back to the add points tool.

ill try out the upgrade.

cheers!

https://user-images.githubusercontent.com/86493327/194924723-f9faf272-095e-4f55-8393-c95c5faf23c9.MP4

**Comment by weertman** [comment]
so, I ran the update and it looks like it is fixed!

**Comment by jeylau** [comment]
Awesome! Thanks for letting me know!
