### ISSUE TITLE
Some issues when labeling the data

### ISSUE THREAD

**Issue by zhoumu53** [DeepLabCut/napari-deeplabcut#52]
When our collaborator labeled the data, they meet some issues with the GUI:

`When doing the labeling with Napari, if I save by choosing 'save all layers', the app crashes and closes. It seems to do it fine when I choose 'save current layer'.`

**Comment by jeylau** [comment]
Yeah, only the Points layer (the one containing the annotation) should be saved, the docs are pretty explicit https://github.com/DeepLabCut/napari-deeplabcut#save-layers

**Comment by zhoumu53** [comment]
Thanks!!! I will let them know.
