### ISSUE TITLE
frame extraction issue

### ISSUE THREAD

**Issue by ramonhypolito** [DeepLabCut/napari-deeplabcut#67]
I am having trouble cropping the videos through the GUI. It does nos allow me to even extract the frames in both manual or automatic extraction mode.

When I disable the frame cropping it works.

**Comment by jeylau** [comment]
Hey @ramonhypolito, could you share some more details with me? What steps should I take so I could try to reproduce this issue?

**Comment by jeylau** [comment]
I think you are referring to DeepLabCut project management GUI; frame extraction and selection of cropping coordinates work fine in `napari-deeplabcut`, so I'll close this issue.

**Comment by MMathisLab** [comment]
but lets check in the project manager gui please
