### ISSUE TITLE
Extract outlier frames Error

### ISSUE THREAD

**Issue by stofe95** [DeepLabCut/napari-deeplabcut#69]
I'm getting the following error when trying to extract outlier frames (deeplabcut version 2.3.3, pandas version 2.0.0). This seems to be from a change in pandas 2.0.0 because it works fine when I downgrade to pandas 1.5.3

File ~\.conda\envs\DEEPLABCUT\lib\site-packages\deeplabcut\refine_training_dataset\outlier_frames.py:408, in extract_outlier_frames(config, videos, videotype, shuffle, trainingsetindex, outlieralgorithm, frames2use, comparisonbodyparts, epsilon, p_bound, ARdegree, MAdegree, alpha, extractionalgorithm, automatic, cluster_resizewidth, cluster_color, opencv, savelabeled, copy_videos, destfolder, modelprefix, track_method)
    406 temp_dt = df_temp.diff(axis=0) ** 2
    407 temp_dt.drop("likelihood", axis=1, level="coords", inplace=True)
--> 408 sum_ = temp_dt.sum(axis=1, level=1)
    409 ind = df_temp.index[(sum_ > epsilon**2).any(axis=1)].tolist()
    410 Indices.extend(ind)

...

TypeError: sum() got an unexpected keyword argument 'level'

**Comment by jeylau** [comment]
Thanks for reporting this bug @stofe95! A fix will soon be merged into deeplabcut https://github.com/DeepLabCut/DeepLabCut/pull/2160 😊
