### ISSUE TITLE
Cannot run any cell of Jupyter Notebook after save and close Napari

### ISSUE THREAD

**Issue by Zichen-iit** [DeepLabCut/napari-deeplabcut#70]
Hi everyone.
I'm using napari for deeplabcut. 
After using the function "dlc.label_frames(config_path)", the napari came out, and I resumed the labeling and saved the layer with label. Then I closed the napari. Seems everything goes well. 
But when I tried to re-open napari and continue the labeling, I find out that non of the cell in the Jupyter cannot run. I have to restart Jupyter.
![image](https://user-images.githubusercontent.com/131868181/234546197-76f4814d-8249-494b-b658-07ec53aff777.png)
It was stuck like this.

Any advice?
Thanks a lot.

**Comment by jeylau** [comment]
Hello @Zichen-iit, sorry for the delay in getting back to you. I tried this with the new version of `napari-deeplabcut`, and it worked fine. I could label some frames, save and close the GUI, and reopen it multiple times without problem. I expect the release today or tomorrow, it should work fine for you after updating 😊

**Comment by jeylau** [comment]
Working fine with the just released v0.2.0 of `napari-deeplabcut`. I'll close, but feel free to reopen it if you encounter some issues.
