### ISSUE TITLE
How to add additional body part labels?

### ISSUE THREAD

**Issue by nitinseshadri** [DeepLabCut/napari-deeplabcut#77]
Hi,

I have a few videos that I've already labeled in the napari GUI. Now, I want to add an additional body part label to the videos. I edited config.yaml with the new body part; however, when I go to add it to the videos, it doesn't show up in napari's list of labels. Is there anything I need to do to make the new labels show up in napari?

EDIT: I am using the latest commit on DeepLabCut's github repository as of June 14. Tried on both macOS 13 Ventura and Windows 10 22H2.

Thanks!

**Comment by jeylau** [comment]
Hi @nitinseshadri, to let napari know of your new body part, load your annotated data and images in napari as usual and, afterwards, drop the config.yaml onto the canvas: this will refresh all dropdown menus. I'd also encourage you to get the most recent `napari-deeplabcut` code with `pip install git+https://github.com/DeepLabCut/napari-deeplabcut.git`, so you get the latest bug fixes 😊

**Comment by nitinseshadri** [comment]
Thanks for the tip! I'll try it out and let you know if it works.

**Comment by nitinseshadri** [comment]
It works! Thanks for your help.
