### ISSUE TITLE
extract_frames error 

### ISSUE THREAD

**Issue by fontaineg** [DeepLabCut/napari-deeplabcut#82]
Hi, I'm new to deeplabcut and am getting stuck with the extract_frames command. I have created a project with one .avi video file and have not modified the config.yaml file. When manually extracting frames napari opens but when I try to open files I encounter the following errors:

In [3]: deeplabcut.extract_frames(config_path, ‘manual’)
Installed qt6 event loop hook.
WARNING: DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family=“MS Sans Serif”, pointsize=12, pixelsize=16, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT(“MS Sans Serif”, lfWidth=0, lfHeight=-16) dpi=144

Traceback (most recent call last):
File “C:\Users\FG\anaconda3\envs\deeplabcut\lib\site-packages\napari_qt\qt_viewer.py”, line 735, in _open_files_dialog
filenames, _ = dlg.getOpenFileNames(
AttributeError: PySide6.QtWidgets.QFileDialog.getOpenFileNames(): unsupported keyword ‘directory’

This is the error message from opening the labeled-data folder:
OSError: No supported images were found.

There is also an error when automatically running extract_frames:

File C:\Users\FG\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\generate_training_dataset\frame_extraction.py:273, in extract_frames(config, mode, algo, crop, userfeedback, cluster_step, cluster_resizewidth, cluster_color, opencv, slider_width, config3d, extracted_cam, videos_list)
    271 elif mode == "automatic":
    272     config_file = Path(config).resolve()
--> 273     cfg = auxiliaryfunctions.read_config(config_file)
    274     print("Config file read successfully.")
    276     numframes2pick = cfg["numframes2pick"]

File C:\Users\FG\anaconda3\envs\deeplabcut\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.py:210, in read_config(configname)
    206 else:
    207     raise FileNotFoundError(
    208         "Config file is not found. Please make sure that the file exists and/or that you passed the path of the config file correctly!"
    209     )
--> 210 return cfg

UnboundLocalError: local variable 'cfg' referenced before assignment

Please let me know if you have any suggestions!

**Comment by MMathisLab** [comment]
Welcome - what did you pass as the config file path? It must be the full path (and you should edit config to pick body parts :)

**Comment by jeylau** [comment]
Hi @fontaineg, like Mackenzie noted, it looks like the path to your config file may be wrong.
As for the GUI bug, it has been recently fixed with `napari` latest version, and will be available within a couple of days with `napari-deeplabcut` new release.

**Comment by jeylau** [comment]
Hi @fontaineg, you now can `pip install napari-deeplabcut==0.2.0` to get the latest version of the `napari-deeplabcut` plugin!

**Comment by fontaineg** [comment]
Thanks all!
